- Makefile
- msi-ec.c
- use sysfs_emit() instead of sprintf() to prevent buffer overflow
- remove unnecessary ACPI check
- make i and len in ec_read_seq() the same type
- better error handling
- use pr_fmt for convenience
> Introduce changes recommended in the kernel mailing list

- msi-ec.c
**How I tested**: by setting values at the mentioned paths and observing the behavior and also observing `ec` realtime values (`sudo watch -n 0.1 hexdump -C /dev/ec`)
- WebCam:`/sys/devices/platform/msi-ec/webcam`
- WebCam Block:`/sys/devices/platform/msi-ec/webcam_block`
- Battery mode: `/sys/devices/platform/msi-ec/battery_mode`
- Cooler booster: `/sys/devices/platform/msi-ec/cooler_boost`
- CPU Realtime temperature: `/sys/devices/platform/msi-ec/cpu/realtime_temperature`
- GPU Realtime temperature: `/sys/devices/platform/msi-ec/gpu/realtime_temperature`
- Also verified from NVIDIA application.
- Value was non zero when I was utilizing GPU
- GPU Realtime Fan Speed:  `/sys/devices/platform/msi-ec/gpu/realtime_fan_speed`
- Value was non zero when I was utilizing GPU
- Fan Mode: …
> Add MSI Katana GF66 11UC support

- Makefile
- README.md
- msi-ec.c
Debug mode lets the user load the module on unsupported hardware to collect information required to add a new configuration.
Currently has EC dump implemented. This way we won't have to use isw which requires an additional acpi_ec module on some distros.
(!) Depends on #17, first 4 commits are from that PR, so you can review it first.
> Add debug mode

- msi-ec.c
> Add new model: "1594EMS1" MSI Prestige 16 Studio A13VE

- README.md
- msi-ec.c
_Something went wrong with the previous pull request. I'm duplicating it here._
device: `MSI Katana 17 B11UCX-897XRU`
*-family: `GF`
*-version: `REV:1.0`
motherboard: `MS-17L2`
*-firmware: `E17L2IMS.317`
CPU: `11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz`
iGPU: `TigerLake-H GT1 [UHD Graphics]`
dGPU: `GA107 [GeForce RTX 2050]`
EC firmware version: `17L2EMS1.108`
EC_dump in default state:
```
| _0 _1 _2 _3 _4 _5 _6 _7 _8 _9 _a _b _c _d _e _f
-----+------------------------------------------------
0x0_ | 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x1_ | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x2_ | 00 00 00 00 00 00 00 00 0a 05 00 00 00 04 0b 0b
0x3_ | 02 05 00 0d 00 00 50 81 d2 11 88 2c c8 01 c0 00
0x4_ | f8 11 36 00 cb 11 90 fb 78 09 04 2c c1 0b fa 32
0x5_ | 00 00 00 00 00 …
```
> Add `Katana 17 B11UCX (17L2EMS1)` support

- msi-ec.c
Added a new firmware version: 14F1EMS1.116
On latest BIOS version released on 03/07/2023 msi_ec is not allowed to load.
```
$ modprobe -v msi_ec
modprobe: ERROR: could not insert 'msi_ec': Operation not supported
$ journalctl -k | grep "msi_ec\|E14F1IMS"
kernel: DMI: Micro-Star International Co., Ltd. Summit E14Evo A12M/MS-14F1, BIOS E14F1IMS.114 03/07/2023
kernel: msi_ec: Firmware version is not supported: '14F1EMS1.116'
```
> msi-ec: Add Summit E14Evo new firmware

- msi-ec.c
This pull request adds support for msi gp66-11ug, I am guessing that this commit should work with other gp66-11u variants and gp76-11u variants.
> msi-ec : add support gp66-11ug

- msi-ec.c
Adds new versions for Summit E14 Flip Evo A12M. 120 was introduced in June's BIOS update, no mention of any changes in the changelog, everything I tested seems to work fine, I assume 119 won't be different but can't test that
Information from #24
> Add new EC versions

- Makefile
This fixes DKMS automatic rebuilds on kernel update install not working because before, it would attempt to use build files from the currently running kernel (which would no longer exist), instead of the build files of the kernel version being installed.
> Restore TARGET makefile option to specify the kernel version

- msi-ec.c
https://github.com/BeardOverflow/msi-ec/issues/124
Looks like B5M-071XTR and B5M-224XES has the same specifications. They may be compatible but requires further testing.
I managed to find most of the required adresses but it still requires some work to do (like super battery address).
Force pushes are expected.
> Add support for MSI Modern 14 B5M-071XTR

- msi-ec.c
Offsets for my Raider GE77HX. Found by RWEverything, all of them works in Windows and Linux. However, FN key swap returns opposite values.
> Raider GE78HX SmartTouchpad offsets

- msi-ec.c
> Titan 18 HX A14V [1822EMS1]

- 6.11-kernel.patch
- Makefile
- README.md
6.10 - https://www.kernel.org/doc/html/v6.10-rc3/driver-api/driver-model/platform.html#platform-drivers
```
int (*remove)(struct platform_device *);
```
changed to
```
void (*remove)(struct platform_device *);
```
in the latest Linux kernel (6.11)
6.11 - https://www.kernel.org/doc/html/latest/driver-api/driver-model/platform.html#platform-drivers
```
struct platform_driver {
int (*probe)(struct platform_device *);
void (*remove)(struct platform_device *);
void (*shutdown)(struct platform_device *);
int (*suspend)(struct platform_device *, pm_message_t state);
int (*resume)(struct platform_device *);
struct device_driver driver;
const struct platform_device_id *id_table;
bool prevent_deferred_probe;
bool driver_managed_dma;
};
```
> fix type to compile for Kernel 6.11

- msi-ec.c
MSI GS66 12UGS
16V5EMS1.107
```
| _0 _1 _2 _3 _4 _5 _6 _7 _8 _9 _a _b _c _d _e _f
-----+------------------------------------------------
0x0_ | 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x1_ | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x2_ | 00 00 00 00 00 00 00 00 0a 05 00 00 00 04 3b 4b
0x3_ | 03 09 00 0d 03 00 50 81 6a 18 60 3b 71 02 e0 00
0x4_ | 00 00 62 00 81 14 00 00 fb 13 ae 40 1c 0c 00 00
0x5_ | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x6_ | 00 00 00 00 00 00 00 00 3d 00 37 3c 41 46 5a 5f
0x7_ | 64 41 2d 32 3c 41 50 55 64 00 08 07 05 05 05 03
0x8_ | 37 00 32 3c 46 52 5a 5d 64 2d 00 2d 3c 46 50 55
0x9_ | 64 00 03 05 05 06 03 03 02 0f 78 02 0f 78 3e 00
0xa_ | 31 36 56 35 45 4d 53 31 2e 31 30 37 31 32 31 34
0xb_ | 32 30 32 32 31 35 3a 33 30 3a 31 37 00 00 00 08 …
```
> Added support for MSI GS66 12UGS

- msi-ec.c
#43
Thanks to @blenheimears
Feel free to add other addresses if you find them
> Add new model `17Q2IMS1` `Titan GT77 HX 13VH`

- msi-ec.c
Update the 18HX FW versions to prevent `msi_ec: Your firmware version is not supported!`
> Update Titan 18 HX for 115, 116

- msi-ec.c
Instead of dynamically allocating the attribute lists and copying the arrays of attributes, use the custom is_visible function natively supported by sysfs. This also leaves no dynamic memory management in the code, avoiding potential memory issues. The is_visible function is implemented in a similar way to the ASUS and Ideapad drivers' implementations
> Use attribute_group.is_visible to hide unsupported attributes

- README.md
- The current installation instructions can be simplified to adding the module to `boot.extraModulePackages` to install them and then adding the name of the module to `boot.kernelModules` to load it. 
- The module has also reached the latest stable release and as such `nixos-unstable` is also no longer needed.
> Fix NixOS installation instructions

- msi-ec.c
> Getting the platform driver ready for upstream

- README.md
- msi-ec.c
It does the same thing that charge_control_(start/end)_threshold already do, just more restricted. Presets, if needed, should be provided by userspace utilities.
> Remove the battery_mode attribute

- msi-ec.c
similar to alpha 17 b5eek, values were ones that changes with each shiftmode, but they don't represent the feature itself.
> Fix Delta 15 A5EFK shiftmode

- msi-ec.c
Laptop model: Raider GE67 HX - 12U
EC Dump:
```
❯ sudo hexdump -C /sys/kernel/debug/ec/ec0/io
[sudo] password for ahmed:
00000000  00 80 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  0a 05 00 00 00 00 0b 5b  |...............[|
00000030  83 01 00 0d 01 00 50 81  6a 18 60 3b 71 02 c0 00  |......P.j.`;q...|
00000040  35 0c 4f 00 a3 14 00 00  31 10 99 3e 04 0c f8 43  |5.O.....1..>...C|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  3a 00 32 39 40 47 4e 55  |........:.29@GNU|
00000070  64 19 00 00 0a 19 20 32  50 64 0a 08 08 08 08 08  |d..... 2Pd......|
00000080  37 00 37 3c 41 46 4b 4b  64 0a 00 00 …
```
> Add support for Raider GE67 HX - 12U

- msi-ec.c
> `Thin GF63 12U/V` `16R8IMS1.1` new version, fix shifts, fn_win invert

- msi-ec.c
I have added code  for the MSI Summit A16 AI+ A3HMTG-035 as far as I could figure out the values. I have added MSI_EC_ADDR_UNSUPP for everything I could not figure out with the MSI center app.
> add MSI Summit A16 AI+ A3HMTG-035

- msi-ec.c
closes #7
Experimental format for adding new device generation which not have breaking changes
> Add `GF65 Thin 10UE` `16W2EMS1` as successor of `16W1EMS1`

- msi-ec.c
everything matches here. first, compared the values on rweverything, then added the line and built the kernel. features work just fine, no need to add new addresses
> Add Crosshair 17 B12UGZ

- Makefile
- msi-ec.c
| Source | Gen 1      | Gen 2      |
| ------ | ---------- | ---------- |
| 0      | CONF_G1_0  |            |
| 1      | CONF_G1_1  |            |
| 2      |            | CONF_G2_0  |
| 3      |            | CONF_G2_1  |
| 4      |            | CONF_G2_2  |
| 5      | CONF_G1_2  |            |
| 6      | CONF_G1_3  |            |
| 7      | CONF_G1_4  |            |
| 8      |            | CONF_G2_3  |
| 9      | CONF_G1_5  |            |
| 10     |            | CONF_G2_4  |
| 11     |            | CONF_G2_5  |
| 12     |            | CONF_G2_6  |
| 14     |            | CONF_G2_7  |
| 16     | CONF_G1_6  |            |
| 17     |            | CONF_G2_8  |
| 21     | CONF_G1_7  |            |
| 23     | CONF_G1_8  |            |
| 25     |            | CONF_G2_9  |
| 27     | …
> Reorder and group devices
