BeardOverflow/msi-ec

msi-ec.c

Added a new firmware version: E1592IMS.10F

Remove BIOS versions from allowed firmware list

---

msi-ec.c

Fix negative start threshold

---

msi-ec.c

Add a config for GF63 Thin 11UC (16R6EMS1.104)

---

msi-ec.c

Filter out unsupported cpu and gpu entries

---

README.md
msi-ec.c

waiting for review #90
EC map analysis here: https://gist.github.com/heinthanth/7f4d527b54a845facf0c31862cee896d
quirks: win key swapped in EC

Add new model "15K1IMS1.110" MSI CYBORG 12 A12VF

---

msi-ec.c

#103 tested and ready for merge
Changelog:
+ add keyboard backlight
+ fix shifts
+ add cam hard lock address (this model has hardware toggle switch)

Add new/old versions for "summit e14 evo a12m" 14F1EMS1 114-118, various fixes

---

.github/ISSUE_TEMPLATE/support_request.yml

@teackot Finally I found the way how to allow people to share dumps without unnecessary formatting. [Try here](https://github.com/glpnk/msi-ec/issues/new?assignees=&labels=New+firmware&projects=&template=support_request.yml)

Fix "Support request" issue template

---

msi-ec.c

issue #89 
[checklist](https://github.com/BeardOverflow/msi-ec/issues/89#issuecomment-1817595636)

add new model "15HKEMS1.104" Modern 15 B7M

---

msi-ec.c

No breaking changes, dump and changelog in #114

Update GF63 Thin 11UC (16R6EMS1.106, 16R6EMS1.107)

---

msi-ec.c

Just merge right away, my error

Remove unwanted tabs after `.invert`

---

msi-ec.c

where does a man go in these hard times? to the left where nothing is left? or to the right where nothing is right?

invert Fn/Win keys

---

msi-ec.c

fixes issue https://github.com/BeardOverflow/msi-ec/issues/163

Add support for GL75 Leopard

---

msi-ec.c

Added bravo 15 B7ED(158PIMS1.112) to supported devices

---

msi-ec.c

Add firmware version for Modern 15 A11M.
All tested settings work as expected (webcam, battery).

Add Modern 15 A11M ec firmware version "1552EMS1.119"

---

msi-ec.c

added mutexes for  functions where a race condition could happen.

added mutexes for functions that can race themselves

---

msi-ec.c

Example:
```
| _0 _1 _2 _3 _4 _5 _6 _7 _8 _9 _a _b _c _d _e _f
-----+------------------------------------------------
0x0_ | 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
0x1_ | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
0x2_ | 00 00 00 00 00 00 00 00 0a 05 00 00 08 2c 0b 0a  |.............,..|
0x3_ | 02 05 00 0d 00 00 50 81 c2 11 28 3c c8 01 c0 00  |......P...(<....|
0x4_ | bc 11 3c 00 5d 0f a0 fc 1d 09 2d 3b f4 0b c0 44  |..<.].....-;...D|
0x5_ | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
0x6_ | 00 00 00 00 00 00 00 00 2c 00 28 32 3c 50 55 5a  |........,.(2<PUZ|
0x7_ | 64 32 00 2d 32 4b 55 6e 78 57 05 08 08 12 03 03  |d2.-2KUnxW......|
0x8_ | 00 00 2d 32 3c 41 46 4b 64 00 00 32 3c 4b 50 5a  |..-2<AFKd..2<KPZ|
0x9_ | …
```

Add an ASCII overview to ec_dump

---

README.md
ec_memory_configuration.h
msi-ec.c

Code cleanup before implementing Fan curve HWMON API

---

msi-ec.c

#105 #173
+ Added "1822EMS1.115" version
+ Disabled Keyboard Backlight because it's RGB

Add `1822EMS1.115` version, remove keyboard backlight support from config 28

---

msi-ec.c

add 105 version to 14DKEMS1

---

msi-ec.c

New device `GF65 Thin 9SEXR` `16W1EMS1`

---

msi-ec.c

Add Alpha 17 C7VF

---

msi-ec.c

Made using Windows method (using MSI app & RWEverything)
the only thing that I am not able to test is fan_mode, I cannot see it in MSI app but 0xd4 is always in auto so I guess it is correct

Add Bravo 15 C7UCX

---

msi-ec.c

Add `GF63 THIN 10SC(XR) / 10UC` `16R5EMS1`

---

msi-ec.c

add `Katana GF66 12UC` `1584EMS1.112`

---

msi-ec.c

fixes https://github.com/BeardOverflow/msi-ec/issues/294

Add support for Bravo 15 B5ED

---

msi-ec.c

fixes https://github.com/BeardOverflow/msi-ec/issues/257

Add GS66 Stealth 10SFS support

---

msi-ec.c

fixes https://github.com/BeardOverflow/msi-ec/issues/306

Add support for Prestige 14 Evo B13M and update few devices

---

msi-ec.c

fixes https://github.com/BeardOverflow/msi-ec/issues/335#issuecomment-2924649023

shift mode fix (Katana 15 B13VFK)

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/support_request.yml

Update Issue and Bug template

---

msi-ec.c

fixes https://github.com/BeardOverflow/msi-ec/issues/261 and https://github.com/BeardOverflow/msi-ec/issues/115

Add support for Bravo 15 B5DD

---

msi-ec.c

fixes https://github.com/BeardOverflow/msi-ec/issues/308

Add new fw version to Bravo 15 B7ED

---

msi-ec.c

Add GF65 Thin 10SCSXR / 10SD(R)

---

msi-ec.c

fixes https://github.com/BeardOverflow/msi-ec/issues/339

Add  16V3EMS1.106 to config52

---

msi-ec.c

Broken features:
- Keyboard backlight
---
This is WorkInProgress as I haven't tested all the features yet. The commit message will be amended if more features are found broken.
Fixes: BeardOverflow/msi-ec#219

WIP: feat(GF63_Thin_9SC): Enable firmware v100, some features broken

---

msi-ec.c

fixes https://github.com/BeardOverflow/msi-ec/issues/376

add 17S1IMS1.113 to conf40

---

msi-ec.c

Add 16V4EMS1.116 to conf 4

---

msi-ec.c

Add versions under "update" label
conf 9 - 14JKEMS1
close #197 
close #324 
conf 11 - 16S6EMS1
close #343 
conf 18 - 15HKEMS1
close #346 
close #351 
conf 19
+ 1543EMS1
close #400 
+ 17K3EMS1
close #111
conf 29 - 16V5EMS1
close #385 
conf 35 - 15M2IMS1
close #305
conf 44 - 17LNIMS1
close #358 
conf 48 - 158NIMS1
close #96
close #347 
close #370 
conf 54 - 16R8IMS2
close #298
---
Add new devices, similar to supported from "mirror" section
conf 1
+ 17F4EMS2
close #248
+ 17F3EMS2
close #297
conf 14 - 17L1EMS1
close #121
close #256
close #230#issuecomment-2734563214
conf 19 - 17K4EMS1
close #333
close #338 
dup #353
close #394
conf 36 - 1585EMS2
close #401
conf 38 - 17E8EMS1 - removed BIOS
conf 40 - 17S1IMS2
close #236
conf 50 - 1583EMS1
close #171
close #362
close #398
close #404
conf 55 - …

update supported versions, add similar models

---

msi-ec.c

16S3EMS1 - conf 0
close #160
1541EMS1 - conf 6
close #263 
17L3EMS1 - conf 14
close #410
close #429
17L4EMS1 - conf 14
close #269
16R1EMS1 - conf 21
close #383
16Q2EMS1 - conf 31
close #361
14C4EMS1 - conf 34
close #245
15M1IMS1 - conf 37
close #422
15M3EMS1 - conf 37
close #312
close #320
close #326
close #364
close #435
16R7IMS1 - conf 39
close #313
17L5EMS1 - conf 44
close #80
close #202
close #220
17L5EMS2 - conf 44
close #381
16R5EMS1 - conf 49
close #436
1584EMS1 - conf 50
close #432
158MEMS1 - conf 51
close #415
16RKIMS1 - conf 54
close #413
17G3EMS1 - conf 55
close #423

add similar devices, merge identical configs
